### ISSUE TITLE
java.lang.Error: Must initialize with FileSystemProvider.installDefaultProvider()

### ISSUE THREAD

**Issue by amarcakic** [zhanghai/AndroidRetroFile#1]
Hello, 

I am backporting an application from API level 28 to API level 22 and decided to use AndroidRetroFile to help with the IO related tasks for files, but i get the following error when the method is called.

06-18 03:54:04.595 2614-3195/com.package.appname E/AndroidRuntime: FATAL EXCEPTION: IntentService[ExportService]
    Process: com.package.appname, PID: 2614
    java.lang.Error: Must initialize with FileSystemProvider.installDefaultProvider()

I have tried to provide the default file provider, and thought i have it by initializing an object of FileProvider, and getting the object, but it seems it does not solve the issue.

I cannot find documentation regarding this issue on how to provide the default FileSystemProvider for use with this plugin.

**Comment by zhanghai** [comment]
See
https://github.com/zhanghai/MaterialFiles/blob/master/app/src/main/java/me/zhanghai/android/files/provider/FileSystemProviders.java#L22
https://github.com/zhanghai/MaterialFiles/blob/master/app/src/main/java/me/zhanghai/android/files/provider/linux/LinuxFileSystemProvider.java#L33

Note that as mentioned in README, this library doesn't backport the default FileSystemProvider implementation, and in MaterialFiles I've implemented all the functionalities myself.

**Comment by amarcakic** [comment]
so to get this straight,
i would have to get all the different file system providers as seen in Material Files and their required classes they use to get it to work?

**Comment by zhanghai** [comment]
Disclaimer: I'm not a lawyer and the following is not legal advice.

In MaterialFiles the LocalLinuxFileSystemProvider implements the actual provider. But it's complicated and tailored to the need of this file manager app. It's also GPL 3 so if you use that code your code also need to be open sourced under GPL 3.

On the other hand, you can try to backport the OpenJDK implementation, which should be mostly free of bugs and licensed under GPL 2 with classpath exception. If you reference your backport as a jar dependency you might not need to open source your own code (the backport might need to be open- sourced under GPL 2 with classpath exception though).

To get to this straight, this library alone doesn't solve backporting the NIO file API on Android. I created it mostly to reference it as a dependency and retain the possibility to license MaterialFiles otherwise (e.g. GPL 3, as it's not compatible with GPL 2), and just in casd someone has exactly the same kind of need as me.

**Comment by amarcakic** [comment]
Oh man i really hoped it would solve my backporting problems.
What would be the fastest way to get an alternative then to the File api given in Java 8?
i mostly need the ability to create output.json file for logs

**Comment by zhanghai** [comment]
I think plain java.io.File is enough for logging.
